// SPDX-License-Identifier: Apache-2.0
// test_eam.cpp — tests for EAM/alloy potential.
#include <gtest/gtest.h>

#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>

#include "core/math.hpp"
#include "core/types.hpp"
#include "io/lammps_data_reader.hpp"
#include "neighbors/neighbor_list.hpp"
#include "potentials/eam_alloy.hpp"

#ifndef TDMD_TEST_DATA_DIR
#error "TDMD_TEST_DATA_DIR must be defined"
#endif

static std::string data_dir() { return TDMD_TEST_DATA_DIR; }

using namespace tdmd;
using namespace tdmd::potentials;

TEST(EamAlloy, ReadSetfl) {
  EamAlloy eam;
  ASSERT_NO_THROW(eam.read_setfl(data_dir() + "/Cu_mishin1.eam.alloy"));
  EXPECT_EQ(eam.ntypes(), 1);
  EXPECT_NEAR(eam.cutoff(), 5.50679, 0.001);
}

TEST(EamAlloy, TwoAtomForces) {
  // Two Cu atoms at distance 2.556 A (FCC nearest-neighbor).
  // Forces should be equal and opposite, nonzero.
  EamAlloy eam;
  eam.read_setfl(data_dir() + "/Cu_mishin1.eam.alloy");

  SystemState state;
  state.resize(2);
  state.box.lo = {0, 0, 0};
  state.box.hi = {20, 20, 20};
  state.box.periodic = {true, true, true};
  state.positions[0] = {8.0, 10.0, 10.0};
  state.positions[1] = {10.556, 10.0, 10.0};
  state.types[0] = 1;
  state.types[1] = 1;
  state.ids[0] = 1;
  state.ids[1] = 2;
  state.masses = {0, 63.546};

  neighbors::NeighborList nlist;
  nlist.build(state.positions.data(), state.natoms, state.box,
              eam.cutoff(), real{0.5});

  real pe = eam.compute_forces(state, nlist);

  // Energy should be negative (bound state).
  EXPECT_LT(pe, 0.0);

  // Newton 3rd law.
  EXPECT_NEAR(state.forces[0].x + state.forces[1].x, 0.0, 1e-10);
  EXPECT_NEAR(state.forces[0].y + state.forces[1].y, 0.0, 1e-10);
  EXPECT_NEAR(state.forces[0].z + state.forces[1].z, 0.0, 1e-10);

  // Forces should be nonzero (not at exact equilibrium).
  EXPECT_GT(std::abs(state.forces[0].x), 1e-6);
}

// VL-10: synthetic 2-element setfl generator.
//
// Writes a minimal but valid setfl file with two elements A and B whose
// functional forms are DELIBERATELY distinct, so that any confusion in the
// type-to-element mapping produces measurably different forces. Returns the
// path to the generated file.
//
// Functional design:
//   F_A(rho)    = -sqrt(rho)                    (baseline Finnis-Sinclair)
//   F_B(rho)    = -2 * sqrt(rho)                (2x deeper embedding)
//   rho_A(r)    = exp(-r)                       (baseline density)
//   rho_B(r)    = 3 * exp(-0.8 * r)             (3x amplitude, slower decay)
//   phi_AA(r)*r = 0.5 * exp(-2r)
//   phi_BB(r)*r = 1.5 * exp(-1.8r)
//   phi_AB(r)*r = 1.0 * exp(-1.9r)              (all three distinct)
//
// Because all six functions differ, any permutation of the [1,2] type labels
// on an A+B configuration must change forces. Unlike a real fitted potential,
// no physical meaning is claimed — the goal is bit-detectable type distinction.
static std::string write_synthetic_ab_setfl() {
  namespace fs = std::filesystem;
  fs::path tmp = fs::temp_directory_path() / "tdmd_test_ab.eam.alloy";
  std::ofstream f(tmp);
  if (!f) throw std::runtime_error("cannot write " + tmp.string());

  constexpr int kNrho = 500;
  constexpr double kDrho = 0.01;
  constexpr int kNr = 500;
  constexpr double kDr = 0.012;  // cutoff ~ 500 * 0.012 = 6.0
  constexpr double kCutoff = 6.0;

  f.precision(15);
  f << std::scientific;

  // Header (3 comment lines).
  f << "# synthetic A-B EAM/alloy for VL-10 mapping test\n";
  f << "# do not use for physics\n";
  f << "# generated by tdmd test harness\n";

  // Line 4: ntypes + element names.
  f << "2 A B\n";

  // Line 5: Nrho drho Nr dr cutoff
  f << kNrho << " " << kDrho << " " << kNr << " " << kDr << " " << kCutoff
    << "\n";

  // Element A block: header + embedding F(rho) + density rho(r).
  f << "1 10.0 3.0 fcc\n";
  for (int i = 0; i < kNrho; ++i) {
    double rho = i * kDrho;
    f << (-std::sqrt(rho)) << "\n";
  }
  for (int i = 0; i < kNr; ++i) {
    double r = i * kDr;
    f << std::exp(-r) << "\n";
  }

  // Element B block.
  f << "2 20.0 3.5 fcc\n";
  for (int i = 0; i < kNrho; ++i) {
    double rho = i * kDrho;
    f << (-2.0 * std::sqrt(rho)) << "\n";
  }
  for (int i = 0; i < kNr; ++i) {
    double r = i * kDr;
    f << (3.0 * std::exp(-0.8 * r)) << "\n";
  }

  // Pair block (upper triangle): AA, AB, BB — as r*phi(r).
  // phi_AA(r)*r = 0.5 * exp(-2r)
  for (int i = 0; i < kNr; ++i) {
    double r = i * kDr;
    f << (0.5 * std::exp(-2.0 * r)) << "\n";
  }
  // phi_AB(r)*r = 1.0 * exp(-1.9r)
  for (int i = 0; i < kNr; ++i) {
    double r = i * kDr;
    f << (1.0 * std::exp(-1.9 * r)) << "\n";
  }
  // phi_BB(r)*r = 1.5 * exp(-1.8r)
  for (int i = 0; i < kNr; ++i) {
    double r = i * kDr;
    f << (1.5 * std::exp(-1.8 * r)) << "\n";
  }

  f.close();
  return tmp.string();
}

// VL-10: Parse a 2-element synthetic setfl.
//
// Sanity check: the reader must accept the file, report ntypes=2, and report
// a cutoff close to the declared value. If this fails, downstream mapping
// tests cannot be trusted (they'd be testing a broken parser).
TEST(EamAlloy, SyntheticAbSetflParses) {
  std::string path = write_synthetic_ab_setfl();
  EamAlloy eam;
  ASSERT_NO_THROW(eam.read_setfl(path));
  EXPECT_EQ(eam.ntypes(), 2);
  EXPECT_NEAR(eam.cutoff(), 6.0, 0.01);
  std::filesystem::remove(path);
}

// VL-10: Mapping permutation is NOT a no-op.
//
// On a 4-atom mixed A/B configuration, computing forces with types [1,2,1,2]
// must produce materially different forces than with types [2,1,2,1]. This
// is the load-bearing negative test from the Comprehensive Test Suite Design
// doc (Test P4): "Permuting mapping must change energies/forces."
//
// The naive single-element EAM test cannot detect mapping bugs because every
// atom resolves to the same spline table regardless of mapping. A fully
// general multi-element setfl is required — we generate one synthetically.
TEST(EamAlloy, MappingPermutationChangesForces) {
  std::string path = write_synthetic_ab_setfl();
  EamAlloy eam;
  eam.read_setfl(path);
  ASSERT_EQ(eam.ntypes(), 2);

  // 4-atom configuration, mixed A/B, well within cutoff.
  SystemState state;
  state.resize(4);
  state.box.lo = {0, 0, 0};
  state.box.hi = {12, 12, 12};
  state.box.periodic = {true, true, true};
  state.positions[0] = {2.0, 6.0, 6.0};
  state.positions[1] = {4.5, 6.0, 6.0};
  state.positions[2] = {6.0, 4.5, 6.0};
  state.positions[3] = {6.0, 6.0, 7.8};
  state.ids = {1, 2, 3, 4};
  state.masses = {0, 10.0, 20.0};  // index 0 unused, 1=A, 2=B

  neighbors::NeighborList nlist;
  nlist.build(state.positions.data(), state.natoms, state.box,
              eam.cutoff(), real{0.5});

  // Configuration 1: types [1, 2, 1, 2]
  state.types = {1, 2, 1, 2};
  for (auto& ff : state.forces) ff = {0, 0, 0};
  real pe_a = eam.compute_forces(state, nlist);
  auto forces_a = state.forces;

  // Configuration 2: types [2, 1, 2, 1] — swapped.
  state.types = {2, 1, 2, 1};
  for (auto& ff : state.forces) ff = {0, 0, 0};
  real pe_b = eam.compute_forces(state, nlist);
  auto forces_b = state.forces;

  // Energies must differ by a physically meaningful amount (not just ulp).
  EXPECT_GT(std::abs(pe_a - pe_b), 1e-3)
      << "permuting types [1,2,1,2] -> [2,1,2,1] must change PE; got "
      << pe_a << " vs " << pe_b;

  // At least one force component must differ by more than 1e-3 eV/A
  // (rules out any chance of a ulp-level coincidence).
  double max_component_diff = 0.0;
  for (std::size_t i = 0; i < forces_a.size(); ++i) {
    const double dx = std::abs(static_cast<double>(forces_a[i].x) -
                               static_cast<double>(forces_b[i].x));
    const double dy = std::abs(static_cast<double>(forces_a[i].y) -
                               static_cast<double>(forces_b[i].y));
    const double dz = std::abs(static_cast<double>(forces_a[i].z) -
                               static_cast<double>(forces_b[i].z));
    max_component_diff = std::max({max_component_diff, dx, dy, dz});
  }
  EXPECT_GT(max_component_diff, 1e-3)
      << "mapping permutation did not change any force component";

  std::filesystem::remove(path);
}

// VL-10: All-same-type mapping is invariant under element relabeling.
//
// Complement to the permutation test. If ALL atoms are type 1 (element A),
// the resulting forces must be bit-identical regardless of whether the setfl
// lists A first or we pretend A is the second element. This cannot be tested
// with a single setfl file — but we CAN test that mapping [1,1,1,1] vs
// [2,2,2,2] in the A-B setfl produces forces that differ (because atoms are
// now B-B instead of A-A, which has different splines). Conversely, [1,1,1,1]
// computed twice must match exactly (idempotence).
TEST(EamAlloy, SameMappingIsDeterministic) {
  std::string path = write_synthetic_ab_setfl();
  EamAlloy eam;
  eam.read_setfl(path);

  SystemState state;
  state.resize(3);
  state.box.lo = {0, 0, 0};
  state.box.hi = {12, 12, 12};
  state.box.periodic = {true, true, true};
  state.positions[0] = {3.0, 6.0, 6.0};
  state.positions[1] = {5.5, 6.0, 6.0};
  state.positions[2] = {6.0, 4.0, 7.0};
  state.ids = {1, 2, 3};
  state.masses = {0, 10.0, 20.0};

  neighbors::NeighborList nlist;
  nlist.build(state.positions.data(), state.natoms, state.box,
              eam.cutoff(), real{0.5});

  // Run 1 with types [1,1,1].
  state.types = {1, 1, 1};
  for (auto& ff : state.forces) ff = {0, 0, 0};
  real pe1 = eam.compute_forces(state, nlist);
  auto forces1 = state.forces;

  // Run 2 with same types [1,1,1] — must be bit-identical.
  for (auto& ff : state.forces) ff = {0, 0, 0};
  real pe2 = eam.compute_forces(state, nlist);
  EXPECT_EQ(pe1, pe2);
  for (std::size_t i = 0; i < forces1.size(); ++i) {
    EXPECT_EQ(forces1[i].x, state.forces[i].x);
    EXPECT_EQ(forces1[i].y, state.forces[i].y);
    EXPECT_EQ(forces1[i].z, state.forces[i].z);
  }

  // Run 3 with types [2,2,2] — same ATOM pattern, different ELEMENT.
  // Must produce different energy (B-B pair phi vs A-A pair phi).
  state.types = {2, 2, 2};
  for (auto& ff : state.forces) ff = {0, 0, 0};
  real pe3 = eam.compute_forces(state, nlist);
  EXPECT_GT(std::abs(pe1 - pe3), 1e-3)
      << "[1,1,1] vs [2,2,2] must differ (different elements, different phi)";

  std::filesystem::remove(path);
}

// VL-11: Embedding density consistency (neighbor list vs brute force).
//
// From Comprehensive Test Suite Design doc (test E2): "compute per-atom
// density contributions two ways (direct sum and neighbor list) and compare".
// The point is NOT to test the spline (FccBulkEnergy covers that). It is to
// test **iteration coverage**: does the neighbor list visit every (i, j) pair
// within cutoff that the density function needs? A missing entry — because of
// a stale half-list, a wrong skin, or a cell-boundary off-by-one — would
// silently drop density contributions and the many-body force path would
// return subtly wrong embedding terms.
//
// This is EAM-specific because the density is accumulated once per neighbor
// pair; for pair-additive potentials (Morse), a missing neighbor is the same
// as a wrong PE which the existing run0-force-match test would catch. For
// EAM, a missing neighbor on atom i's density list also changes atom j's
// force through the embedding derivative fp_j — the error cascades in ways
// that are hard to attribute without this direct check.
TEST(EamAlloy, EmbeddingDensityMatchesBruteForce) {
  EamAlloy eam;
  eam.read_setfl(data_dir() + "/Cu_mishin1.eam.alloy");

  // 256-atom Cu FCC — same input VL-2 grades against.
  auto state = io::read_lammps_data(data_dir() + "/cu_fcc_256.data");
  const real rc = eam.cutoff();
  const real rc_sq = rc * rc;

  neighbors::NeighborList nlist;
  nlist.build(state.positions.data(), state.natoms, state.box, rc, real{0.5});

  // --- Path A: rho_i via neighbor list (what the engine does).
  std::vector<double> rho_nlist(static_cast<std::size_t>(state.natoms), 0.0);
  const auto& density_tables = eam.density();
  const Vec3D box_size = state.box.size();
  for (i64 i = 0; i < state.natoms; ++i) {
    const i32 cnt = nlist.count(i);
    const i32* nbrs = nlist.neighbors_of(i);
    for (i32 k = 0; k < cnt; ++k) {
      const i32 j = nbrs[k];
      PositionVec d = state.positions[static_cast<std::size_t>(j)] -
                      state.positions[static_cast<std::size_t>(i)];
      d = minimum_image(d, box_size, state.box.periodic);
      const double r2 = length_sq(d);
      if (r2 >= static_cast<double>(rc_sq)) continue;
      const real r = static_cast<real>(std::sqrt(r2));

      // Half-list: this pair contributes to both atoms' densities.
      const i32 ti = state.types[static_cast<std::size_t>(i)] - 1;
      const i32 tj = state.types[static_cast<std::size_t>(j)] - 1;
      rho_nlist[static_cast<std::size_t>(i)] += static_cast<double>(
          density_tables[static_cast<std::size_t>(tj)].eval(r));
      rho_nlist[static_cast<std::size_t>(j)] += static_cast<double>(
          density_tables[static_cast<std::size_t>(ti)].eval(r));
    }
  }

  // --- Path B: rho_i via brute force O(N^2) over all (i, j) within cutoff.
  std::vector<double> rho_brute(static_cast<std::size_t>(state.natoms), 0.0);
  for (i64 i = 0; i < state.natoms; ++i) {
    for (i64 j = 0; j < state.natoms; ++j) {
      if (i == j) continue;
      PositionVec d = state.positions[static_cast<std::size_t>(j)] -
                      state.positions[static_cast<std::size_t>(i)];
      d = minimum_image(d, box_size, state.box.periodic);
      const double r2 = length_sq(d);
      if (r2 >= static_cast<double>(rc_sq)) continue;
      const real r = static_cast<real>(std::sqrt(r2));
      const i32 tj = state.types[static_cast<std::size_t>(j)] - 1;
      rho_brute[static_cast<std::size_t>(i)] += static_cast<double>(
          density_tables[static_cast<std::size_t>(tj)].eval(r));
    }
  }

  // Per-atom rho must match within spline-eval round-off.
  double max_abs_diff = 0.0;
  double max_rel_diff = 0.0;
  for (std::size_t i = 0; i < rho_nlist.size(); ++i) {
    const double abs_diff = std::abs(rho_nlist[i] - rho_brute[i]);
    max_abs_diff = std::max(max_abs_diff, abs_diff);
    if (std::abs(rho_brute[i]) > 1e-12) {
      max_rel_diff = std::max(max_rel_diff, abs_diff / std::abs(rho_brute[i]));
    }
  }

  // Tolerance: per-atom rho is ~1 for bulk Cu FCC (dimensionless density
  // units in this setfl). Non-associative float sums of ~12 neighbor
  // contributions, each of order 0.1, produce at most ~1e-13 abs error
  // in double precision. Be generous — 1e-10 absolute is well above noise.
  EXPECT_LT(max_abs_diff, 1e-10)
      << "neighbor-list and brute-force density disagree: max abs diff = "
      << max_abs_diff;
  EXPECT_LT(max_rel_diff, 1e-10);

  // Also: every atom in bulk FCC must have non-trivial density. If rho is
  // zero anywhere, either the neighbor list dropped every neighbor or the
  // test input was broken.
  for (std::size_t i = 0; i < rho_nlist.size(); ++i) {
    EXPECT_GT(rho_nlist[i], 0.01)
        << "atom " << i << " has near-zero density (" << rho_nlist[i]
        << ") — neighbor list may be empty or spline broken";
  }
}

TEST(EamAlloy, FccBulkEnergy) {
  // 256-atom Cu FCC at a=3.615. Cohesive energy should be ~-3.54 eV/atom.
  EamAlloy eam;
  eam.read_setfl(data_dir() + "/Cu_mishin1.eam.alloy");

  auto state = io::read_lammps_data(data_dir() + "/cu_fcc_256.data");

  neighbors::NeighborList nlist;
  nlist.build(state.positions.data(), state.natoms, state.box,
              eam.cutoff(), real{0.5});

  real pe = eam.compute_forces(state, nlist);
  real pe_per_atom = pe / static_cast<real>(state.natoms);

  // Mishin Cu EAM: cohesive energy ~-3.54 eV/atom at a=3.615.
  EXPECT_NEAR(pe_per_atom, -3.54, 0.1)
      << "PE/atom = " << pe_per_atom;
}

// VL-15: setfl parser robustness.
//
// A corrupt or truncated setfl must be rejected with a clear exception — not
// silently parsed into garbage splines, not return random values, not crash.
// The research doc frames this as "fuzz the reader"; for our purposes, the
// interesting failure modes are bounded and enumerable, so we test them
// directly rather than running a fuzzer.
//
// Cases covered:
//   1. Empty file                              -> premature end
//   2. Only comment lines, no ntypes header    -> premature end
//   3. Header valid but zero F(rho) values     -> premature end during array
//   4. Truncated mid-F(rho)                    -> premature end during array
//   5. Truncated just before pair block        -> premature end during array
//
// Cases NOT covered (deliberately):
//   - Wrong ntypes vs declared (e.g. "2 A" -> iss fails on name read and reads
//     garbage; parser's silent tolerance here is a known gap tracked as its
//     own follow-up, not folded into VL-15 to keep scope tight).
//   - Negative Nrho/Nr (resize with negative count is UB at the C++ level
//     before the parser can reject it — needs a guard in the reader itself).
//
// The current reader uses TDMD_THROW for premature-end conditions, which maps
// to std::runtime_error. The tests assert the throw, not a specific message.
static std::string write_file(const std::string& name,
                              const std::string& contents) {
  namespace fs = std::filesystem;
  fs::path tmp = fs::temp_directory_path() / name;
  std::ofstream f(tmp);
  f << contents;
  f.close();
  return tmp.string();
}

TEST(EamAlloy, RejectEmptyFile) {
  std::string path = write_file("tdmd_setfl_empty.eam.alloy", "");
  EamAlloy eam;
  EXPECT_THROW(eam.read_setfl(path), std::runtime_error);
  std::filesystem::remove(path);
}

TEST(EamAlloy, RejectCommentsOnly) {
  std::string path = write_file(
      "tdmd_setfl_comments.eam.alloy",
      "# line 1\n# line 2\n# line 3\n");
  EamAlloy eam;
  EXPECT_THROW(eam.read_setfl(path), std::runtime_error);
  std::filesystem::remove(path);
}

TEST(EamAlloy, RejectMissingEmbeddingArray) {
  // Full header promising Nrho=500 embedding values, but file ends
  // immediately after the per-element header line.
  std::string contents =
      "# c1\n# c2\n# c3\n"
      "1 Cu\n"
      "500 0.01 500 0.012 6.0\n"
      "29 63.546 3.615 fcc\n";
  std::string path = write_file("tdmd_setfl_no_embed.eam.alloy", contents);
  EamAlloy eam;
  EXPECT_THROW(eam.read_setfl(path), std::runtime_error);
  std::filesystem::remove(path);
}

TEST(EamAlloy, RejectTruncatedEmbeddingArray) {
  // Header promises 500 F(rho) values; we provide only 10 then EOF.
  std::string contents =
      "# c1\n# c2\n# c3\n"
      "1 Cu\n"
      "500 0.01 500 0.012 6.0\n"
      "29 63.546 3.615 fcc\n";
  for (int i = 0; i < 10; ++i) contents += "0.0\n";
  std::string path = write_file("tdmd_setfl_trunc_embed.eam.alloy", contents);
  EamAlloy eam;
  EXPECT_THROW(eam.read_setfl(path), std::runtime_error);
  std::filesystem::remove(path);
}

TEST(EamAlloy, RejectMissingPairBlock) {
  // Full embedding + density for element 0, but the pair block (phi*r) is
  // absent entirely — file ends after the last density value.
  std::string contents =
      "# c1\n# c2\n# c3\n"
      "1 Cu\n"
      "50 0.01 50 0.012 0.6\n"
      "29 63.546 3.615 fcc\n";
  for (int i = 0; i < 50; ++i) contents += "-1.0\n";  // F(rho)
  for (int i = 0; i < 50; ++i) contents += "0.5\n";   // rho(r)
  // No phi block.
  std::string path = write_file("tdmd_setfl_no_pair.eam.alloy", contents);
  EamAlloy eam;
  EXPECT_THROW(eam.read_setfl(path), std::runtime_error);
  std::filesystem::remove(path);
}
